import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/app/context/AuthContext";
import { GameProvider } from '@/app/context/GameContext'
import { AdminAuthProvider } from '@/app/context/AdminAuthContext';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Call Of Diagnosis",
  description: "Generated by create next app",
  icons: {
    icon: "/images/cod_logo_icon.png",
    shortcut: "/images/cod_logo_icon.png",
    apple: "/images/cod_logo_icon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AdminAuthProvider>
          <AuthProvider>
            <GameProvider>
              {children}
            </GameProvider>
          </AuthProvider>
        </AdminAuthProvider>
      </body>
    </html>
  );
}
